--10 제약조건 CONSTRAINT.SQL
-- 제약조건: 테이블에 부적절한 자료가 입력되는 것을 방지하기 위해 칼럼마다 정의하는 규칙
-- NOT NULL: NULL을 허용하지 않는다
-- UNIQUE: 중복값을 허용하지 않는다. 항상유일한 값을 갖도록 한다
-- PRIMARY KEY: NOT NULL + UNIQUE. 테이블의 기본키가 된다
-- FOREIGN KEY: 참조하는 테이블의 특정 칼럼에 존재하는 값을 허용
--              외래키로 참조 하려는 컬럼은 반드시 기본키거나 UNIQUE여야 한다
-- CHECK: 직접 원하는 값의 조건을 설정

--제약조건 메타데이터 확인
-- USER_CONSTRAINTS 테이블의 CONSTRAINT_TYPE 칼럼의 값에 따라 어떤 제약조건인지 알 수 있다
--      P: PRIMARY KEY
--      R: FOREIGN KEY
--      U: UNIQUE;
--      C; NOT NULL, CHECK
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='MY_MEMBER';
SELECT * FROM USER_CONSTRAINTS;

--어느 컬럼에 설정되었는지 확인
SELECT * FROM USER_CONS_COLUMNS;


SELECT * FROM MY_MEMBER;

-- 이미 존재하는 테이블에 제약조건 추가하기
-- 제약조건을 추가하려는 칼럼에 제약조건을 만족시키지 못하는 행이 존재하면, 제약조건을 추가할 수 없다.
-- ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 제약조건(컬럼);
ALTER TABLE MY_MEMBER ADD CONSTRAINT MY_MEMBER_MEMNO_PK PRIMARY KEY(MEM_NO);
SELECT * FROM USER_CONSTRAINTS;
DESC MY_MEMBER;
INSERT INTO MY_MEMBER(MEM_NO, MEM_AGE,JOINDATE) VALUES(MY_MEMBER_MEMNO_SEQ.NEXTVAL,123,SYSDATE);
SELECT * FROM MY_MEMBER ORDER BY MEM_NO DESC;
DELETE FROM MY_MEMBER WHERE MEM_NO=106;

-- NOT NULL 제약조건 추가하기
-- NOT NULL 제약조건은 ADD CONSTRAINT가 아니라 MODIFY CONSTRAINT를 사용해야한다
-- NULL 을 허용하는 상태에서 NULL을 허용하지 않는 상태로 변경하는 것이기 때문에 MODIFY를 사용한다
-- ALTER TABLE 테이블명 MODIFY 칼럼명 CONSTRAINT 제약조건명 NOT NULL;
ALTER TABLE MY_MEMBER MODIFY MEM_NAME CONSTRAINT MY_MEMBER_MNAME_NN NOT NULL;



-- 제약조건 제거하기
--ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
ALTER TABLE MY_MEMBER DROP CONSTRAINT MY_BOARD_MEMNO_PK;
-- NOT NULL 제약조선 제거하기
ALTER TABLE MY_MEMBER DROP CONSTRAINT MY_MEMBER_MNAME_NN;



-- 외래키 추가하기
--EMP02와 DEPT02를 생성
DROP TABLE EMP02;
CREATE TABLE EMP02 AS SELECT * FROM EMP;

DROP TABLE DEPT02;
CREATE TABLE DEPT02 AS SELECT * FROM DEPT;

SELECT * FROM EMP02;
SELECT * FROM DEPT02;

--EMP02에 FK추가
-- ALTER TABLE 테이블명 ADD CONTSTRAINT 제약조건명 FOREIGN KEY(칼럼명) REFERENCES 참조할 테이블명(칼럼명);
ALTER TABLE EMP02 ADD CONSTRAINT EMP02_DEPTNO_FK FOREIGN KEY(DEPTNO)REFERENCES DEPT02(DEPTNO);
--"no matching unique or primary key for this column-list"

--FK를 추가하려면 DEPT02의 DEPTNO가 FK 혹은 UNIQUE여아한다
ALTER TABLE DEPT02 ADD CONSTRAINT DEPT02_DEPTNO_UNQ UNIQUE(DEPTNO);

-- FK제약조건이 걸린 칼럼에 NULL값은 허용하지만 존재하지 않는 값은 허용하지 않는다
-- 참조하고 있는 곳에 존재하지 않는 값은 허용하지 않는다
INSERT INTO EMP02 VALUES(1,'TEST','TEST',7782,SYSDATE,0,NULL,NULL);
INSERT INTO EMP02 VALUES(1,'TEST','TEST',7782,SYSDATE,0,NULL,11);



SELECT * FROM MY_MEMBER;
--CHECK 제약조건 추가(원하는 대로 칼럼에 들어갈 값에 대한 조건을 추가할 수 있음)
ALTER TABLE MY_MEMBER ADD CONSTRAINT MY_MEMBER_AGE_CHK CHECK(MEM_AGE BETWEEN 1 AND 999);
INSERT INTO MY_MEMBER VALUES(MY_MEMBER_MEMNO_SEQ.NEXTVAL,'TESTER',-5,SYSDATE);
INSERT INTO MY_MEMBER VALUES(MY_MEMBER_MEMNO_SEQ.NEXTVAL,'TESTER',0,SYSDATE);
INSERT INTO MY_MEMBER VALUES(MY_MEMBER_MEMNO_SEQ.NEXTVAL,'TESTER',-999,SYSDATE);
SELECT * FROM USER_CONSTRAINTS;

ALTER TABLE MY_MEMBER ADD (GENDER VARCHAR2(1) DEFAULT 'M');
SELECT * FROM MY_MEMBER ORDER BY MEM_NO DESC;
ALTER TABLE MY_MEMBER ADD CONSTRAINT MY_MEMBER_GENDER_CHK CHECK(GENDER IN ('M','F','L','G','B','T'));

INSERT INTO MY_MEMBER VALUES(MY_MEMBER_MEMNO_SEQ.NEXTVAL,'TESTER',55,SYSDATE,'F');
INSERT INTO MY_MEMBER VALUES(MY_MEMBER_MEMNO_SEQ.NEXTVAL,'TESTER',55,SYSDATE,'G');



SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='TEST_CONS';
--제약조건 이름이 오라클에서 지정해주는 이름이 된다. 매우불편하다
--테이블 생서과 동시에 제약조건 추가
DROP TABLE TEST_CONS2;
CREATE TABLE TEST_CONS2(
    TNO NUMBER(5) CONSTRAINT CONS2_TNO_PK PRIMARY KEY,
    TNAME VARCHAR2(10) CONSTRAINT CONS2_TNAME_NN NOT NULL,
    GENDER VARCHAR2(1) CONSTRAINT CONS2_GENDER_FK CHECK(GENDER IN ('M','F')),
    JOINDATE DATE DEFAULT SYSDATE
)
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='TEST_CONS2';

CREATE TABLE TEST_CONS3(
    TNO NUMBER(5),
    TNAME VARCHAR2(10),
    GENDER VARCHAR2(1),
    JOINDATE DATE DEFAULT SYSDATE
  CONSTRAINT CONS2_TNO_PK PRIMARY KEY(TNO),
  CONSTRAINT CONS2_GENDER_FK CHECK(GENDER IN ('M','F'))  
)
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='TEST_CONS3';
    -- 만들고 있던 테이블에 맞는 제약조건들을 추가
    -- NOT NULL, CHECK, PRIMARY KEY, FOREIGN KEY(필요하다면 테이블 추가),UNIQUE;
    

SELECT * FROM MY_SCORE;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='MY_SCORE';
SELECT * FROM USER_CONS_COLUMNS;
INSERT INTO MY_SCORE(MY_NO,MY_NAME, MY_AGE,MY_BIRTHDAY,MY_KOR,MY_MATH,MY_ENG) VALUES (10,'홍길동',20,'09/11/20',80,99,100);
DESC MY_SCORE;
INSERT INTO MY_SCORE(MY_NO, MY_AGE,MY_BIRTHDAY) VALUES(MY_SCORE_MY_NO_SEQ.NEXTVAL,23,SYSDATE);
ALTER TABLE MY_SCORE MODIFY MY_NO CONSTRAINT MY_SCORE_MY_NO_NN NOT NULL;
--ALTER TABLE MY_SCORE ADD CONSTRAINT MY_SCORE_MY_NO_PK PRIMARY KEY(MY_NO);
ALTER TABLE MY_SCORE MODIFY MY_NO CONSTRAINT MY_SCORE_MY_AGE_NN NOT NULL;
INSERT INTO MY_SCORE VALUES(MY_SCORE_MY_NO_SEQ.NEXTVAL,'김동완',40,SYSDATE,50,80,100);
ALTER TABLE MY_SCORE ADD CONSTRAINT DEPT02_DEPTNO_UNQ UNIQUE(DEPTNO);
CREATE TABLE TEST_CONS2(
    TNO NUMBER(5) CONSTRAINT CONS2_TNO_PK PRIMARY KEY,
    TNAME VARCHAR2(10) CONSTRAINT CONS2_TNAME_NN NOT NULL,
    GENDER VARCHAR2(1) CONSTRAINT CONS2_GENDER_FK CHECK(GENDER IN ('M','F')),
    JOINDATE DATE DEFAULT SYSDATE
)
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='TEST_CONS2';
