--EX
--07_CREATE TABLE
CREATE TABLE MY_SCORE(
    MY_NAME VARCHAR(10),
    MY_AGE NUMBER(3),
    MY_BIRTHDAY DATE,
    MY_KOR NUMBER(3),
    MY_MATH NUMBER(3),
    MY_ENG NUMBER(3)
);
SELECT * FROM MY_SCORE;
