select * from employees ORDER BY SALARY;
SELECT * FROM countries;
SELECT ROWNUM,EMPLOYEE_ID, FIRST_NAME, LAST_NAME,SALARY
FROM(SELECT ROWNUM RNUM,EMPLOYEE_ID, FIRST_NAME, LAST_NAME,SALARY 
FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC))
WHERE RNUM BETWEEN 2 AND 10;

SELECT ROWNUM RNUM,EMPLOYEE_ID, FIRST_NAME, LAST_NAME,SALARY 
FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC);

SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE 
FROM(SELECT ROWNUM RNUM, EMPLOYEE_ID,FIRST_NAME, LAST_NAME, HIRE_DATE 
FROM (SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE))
WHERE RNUM BETWEEN 1 AND 10
;

SELECT DEPARTMENT_ID,AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT * FROM EMPLOYEES WHERE (JOB_ID, SALARY) IN
(SELECT JOB_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY JOB_ID);