--ORDER BY
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT ROWNUM,EMPLOYEE_ID, FIRST_NAME, LAST_NAME,SALARY 
FROM (SELECT ROWNUM RNUM,EMPLOYEE_ID, FIRST_NAME, LAST_NAME,SALARY
FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC))
WHERE RNUM BETWEEN 2 AND 10
;

--입사일이 가장 빠른 사람부터 10번째 사람까지의 
-- 사원번호, 이름, 급여, 입사일 출력
SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME, LAST_NAME,HIRE_DATE
FROM(SELECT ROWNUM RNUM, EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE
FROM (SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE DESC))
WHERE RNUM BETWEEN 1 AND 10;


SELECT B.* FROM EMPLOYEES A, EMPLOYEES B 
WHERE (SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY A.DEPARTMENT_ID)>
(SELECT B.SALARY FROM EMPLOYEES GROUP BY B.DEPARTMENT_ID)
;

--AVG이름:
--SUM, MIN, MAX, COUNT, STDDEY(표준편차),VARIANCE()-분산
--NVL(열 이름, 기본값) - NULL대체
SELECT COUNT(COMMISSION_PET,0) FROM EMPLOYEES;

SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY)>5000 ;

SELECT * FROM EMPLOYEES WHERE (DEPARTMENT_ID,SALARY)IN
(SELECT DEPARTMENT_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID);

SELECT DEPARTMENT_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

--직무별 최대 급여를 받는 사람의 모든 속성 출력
SELECT * FROM EMPLOYEES WHERE (JOB_ID, SALARY)IN
(SELECT JOB_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY JOB_ID);
