--JOIN.구문
--EMPLOYEES 에서 부서별 평균급여보다 많은사람
SELECT B.* FROM EMPLOYEES A, EMPLOYEES B 
WHERE (SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY A.DEPARTMENT_ID)>
(SELECT B.SALARY FROM EMPLOYEES GROUP BY B.DEPARTMENT_ID)
;
--선생님 풀이
select * from employees e
join 
(SELECT department_id, avg(salary) as avg_salary FROM EMPLOYEES GROUP BY department_id) d
on e.department_id = d.department_id
where e.salary > d.avg_salary;


--부서별 월급 급여에서 월급이 가장 높은 부서의 평균과
-- 가장 낮은 급여 출력
SELECT MAX(ROUND(AVG(SALARY))) HIGHER_SAL, MIN(ROUND(AVG(SALARY))) LOWER_SAL FROM EMPLOYEES  
GROUP BY DEPARTMENT_ID;

SELECT * FROM DEPARTMENTS;

--ON(JOIN절에서 조건)
--테이블이 겹쳐질때 둘다 들어있는 경우(EX. DEPARTMENT_ID) 불러온 것 기준으로 작성
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, E.DEPARTMENT_ID,DEPARTMENT_NAME, CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L 
ON d.location_id=l.location_id
;

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,E.MANAGER_ID FROM EMPLOYEES E 
JOIN EMPLOYEES M
ON E.MANAGER_ID=M.EMPLOYEE_ID;

--매니저만 가려내기 :
-- DISTINCT 명령어: 중복 걸러내기
SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME AS MANAGER_NAME FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN
(SELECT DISTINCT MANAGER_ID FROM EMPLOYEES);


SELECT * FROM EMPLOYEES E 
LEFT JOIN
(
SELECT EMPLOYEE_ID AS MANAGER_ID, EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME AS MANAGER_NAME FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN
(SELECT DISTINCT MANAGER_ID FROM EMPLOYEES)
) M
ON E.MANAGER_ID = M.MANAGER_ID;


--부서별로 별로 평균급여보다 많이 받는 사람 출력
select * from employees e
join 
(SELECT department_id, avg(salary) as avg_salary FROM EMPLOYEES GROUP BY department_id) d
on e.department_id = d.department_id
where e.salary > d.avg_salary;